java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    # Endpoints
    IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
    S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

    # logging vars & healthcheck
    REFORM_ENVIRONMENT: aat
    PACKAGES_ENVIRONMENT: aat
